// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProjectRunner.Infra.Data.Context;

namespace ProjectRunner.Infra.Data.Migrations
{
    [DbContext(typeof(SQLiteContext))]
    [Migration("20210620003318_AddExecutableAndChangeCommandToExecutableArgumentsProjects")]
    partial class AddExecutableAndChangeCommandToExecutableArgumentsProjects
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("ProjectRunner.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Executable")
                        .IsRequired()
                        .HasColumnType("Varchar(255)")
                        .HasColumnName("Executable");

                    b.Property<string>("ExecutableArguments")
                        .IsRequired()
                        .HasColumnType("Varchar(255)")
                        .HasColumnName("ExecutableArguments");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Varchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("Varchar(255)")
                        .HasColumnName("Path");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
